### ISSUE TITLE
Undefined method `empty?' for #<URI::HTTPS:0x000001021d0580>

### ISSUE THREAD

**Issue by andrewhavens** [tpope/heroku-surrogate#3]
I just updated to the latest version and came across this error:

```
Heroku client internal error.
undefined method `empty?' for #<URI::HTTPS:0x000001021d0580>
/usr/local/heroku/ruby/lib/ruby/1.9.1/net/http.rb:1860:in `initialize'
/usr/local/heroku/ruby/lib/ruby/1.9.1/net/http.rb:2093:in `initialize'
/Users/andrew/.heroku/plugins/heroku-surrogate/lib/heroku/command/surrogate.rb:107:in `new'
/Users/andrew/.heroku/plugins/heroku-surrogate/lib/heroku/command/surrogate.rb:107:in `api_request'
/Users/andrew/.heroku/plugins/heroku-surrogate/lib/heroku/command/surrogate.rb:101:in `get_release_info'
/Users/andrew/.heroku/plugins/heroku-surrogate/lib/heroku/command/surrogate.rb:83:in `get_release'
/Users/andrew/.heroku/plugins/heroku-surrogate/lib/heroku/command/surrogate.rb:27:in `index'
/Users/andrew/.heroku/client/lib/heroku/command.rb:212:in `run'
/Users/andrew/.heroku/client/lib/heroku/cli.rb:35:in `start'
/usr/local/bin/heroku:24:in `<main>'
```

**Comment by renguomin** [comment]
ruby version too old?
